services:
  localdb:
    image: postgres:15.1 # you can pick the most recent version available
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onboarding_local

  testdb:
    image: postgres:15.1
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onboarding_test
